/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 plant.gltf 
Author: AllQuad (https://sketchfab.com/AllQuad)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/stand-pot-plant-monstera-deliciosa-d6f166481fa9466fbd288722d0c4df2f
Title: Stand Pot Plant Monstera Deliciosa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./plant.gltf');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Terracotta_Planter_Stand_Terracotta_Planter_Stand_Mat_0.geometry} material={materials.Terracotta_Planter_Stand_Mat} />
          <mesh geometry={nodes.MONSTERA_BIG_MONSTERA_BIG_Mat002_0.geometry} material={materials['MONSTERA_BIG_Mat.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./plant.gltf')
